[package]
name = "iced-hs"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.iced]
# version = "0.12.1"
git = "https://github.com/iced-rs/iced"
rev = "b30d34f"
features = ["advanced", "canvas", "lazy", "tokio"]

[dependencies.tokio]
version = "1.37"
features = ["macros", "rt-multi-thread", "sync", "time"]
