[package]
name = "iced-hs"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.iced]
# version = "0.13"
# temporary fork to provide physical keys
git = "https://github.com/ibaryshnikov/iced"
rev = "8b34f99"
features = ["advanced", "canvas", "lazy", "tokio", "image"]

[dependencies.iced_winit]
# version = "0.13"
git = "https://github.com/ibaryshnikov/iced"
rev = "8b34f99"

[dependencies.iced_widget]
# version = "0.13"
git = "https://github.com/ibaryshnikov/iced"
rev = "8b34f99"

[dependencies.tokio]
version = "1.40"
features = ["macros", "rt-multi-thread", "sync", "time"]
