[package]
name = "iced-hs"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.iced]
# version = "0.12.1"
# temporary fork to provide KeyCode from PhysicalKey
git = "https://github.com/ibaryshnikov/iced"
rev = "ea6f377"
features = ["advanced", "canvas", "lazy", "tokio"]

# winit version should match the version in iced-rs
[dependencies.winit]
git = "https://github.com/iced-rs/winit.git"
rev = "8affa522bc6dcc497d332a28c03491d22a22f5a7"

[dependencies.tokio]
version = "1.37"
features = ["macros", "rt-multi-thread", "sync", "time"]
